apiVersion: webapp.aes.dev/v1
kind: OrgPod
metadata:
  labels:
    app.kubernetes.io/name: orgpod
    app.kubernetes.io/instance: orgpod-sample
    app.kubernetes.io/part-of: aescloud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aescloud
  name: orgpod-sample
spec:
  # TODO(user): Add fields here
